<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "agreement_bill_back".
 *
 * @property integer $id
 * @property integer $agreement_id
 * @property integer $type
 * @property integer $sno
 * @property string $description
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Agreement $agreement
 * @property string $aliasModel
 */
abstract class AgreementBillBack extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'agreement_bill_back';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['agreement_id', 'type', 'sno', 'description'], 'required'],
            [['agreement_id', 'type', 'sno'], 'integer'],
            [['description'], 'string'],
            [['agreement_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Agreement::className(), 'targetAttribute' => ['agreement_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'agreement_id' => Yii::t('models', 'Agreement ID'),
            'type' => Yii::t('models', 'Type'),
            'sno' => Yii::t('models', 'Sno'),
            'description' => Yii::t('models', 'Description'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreement()
    {
        return $this->hasOne(\app\models\Agreement::className(), ['id' => 'agreement_id']);
    }




}
