<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "agreement_bill".
 *
 * @property integer $id
 * @property integer $agreement_id
 * @property integer $agreement_type
 * @property integer $invoice_no
 * @property integer $has_percentage
 * @property string $related_invoice
 * @property string $invoice_date
 * @property string $order_no
 * @property string $work_name
 * @property string $estimate_no
 * @property string $section_name
 * @property string $start_date
 * @property string $complete_date
 * @property string $circle_name
 * @property integer $billing_company_id
 * @property integer $billing_company_state
 * @property integer $billing_company_district
 * @property string $billing_company_gst
 * @property string $base_amount
 * @property integer $schedule
 * @property string $schedule_rate
 * @property string $schedule_amount
 * @property string $total_amount
 * @property string $tax_amount
 * @property string $after_tax_total
 * @property string $penality_amount
 * @property integer $stamp
 * @property integer $tax_on_items
 * @property string $penality_tax
 * @property string $penality_after_tax
 * @property string $advance_paid
 * @property string $payable_amount
 * @property string $tax_note
 * @property string $deduction_note
 * @property string $extra_note
 * @property string $payment_note
 * @property integer $company_id
 * @property string $session
 * @property integer $status
 * @property integer $has_credit_note
 * @property integer $credit_note_invoice_id
 * @property integer $mode_of_transport
 * @property string $transporter
 * @property string $gr_no
 * @property string $vehicle_no
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Agreement $agreement
 * @property \app\models\BillDeduction[] $billDeductions
 * @property \app\models\BillItem[] $billItems
 * @property \app\models\BillTax[] $billTaxes
 * @property \app\models\BillPenality[] $billPenalties
 * @property \app\models\AgreementBillStatus[] $billStatuses
 * @property \app\models\Company $company
 * @property \app\models\BillingCompany $billingCompany
 * @property \app\models\State $billingCompanyState
 * @property \app\models\District $billingCompanyDistrict
 * @property \app\models\SignatureMaster $signature
 * @property \app\models\AgreementBillBack $billBack
 * @property \app\models\AgreementBill $creditNote
 * @property string $aliasModel
 */
abstract class AgreementBill extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'agreement_bill';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['agreement_id','invoice_date', 'base_amount','tax_amount', 'payable_amount', 'company_id', 'session','billing_company_id','billing_company_state','billing_company_district','billing_company_gst','stamp'], 'required'],
            [['agreement_id','agreement_type', 'invoice_no', 'schedule', 'company_id','billing_company_id','billing_company_state','billing_company_district','stamp','status','has_percentage','mode_of_transport','tax_on_items'], 'integer'],
            [['invoice_date', 'start_date', 'complete_date','tax_note','deduction_note','has_credit_note','credit_note_invoice_id','extra_note','payment_note','transporter','gr_no','vehicle_no'], 'safe'],
            [['base_amount', 'schedule_rate', 'schedule_amount','tax_amount','after_tax_total','penality_amount','penality_tax', 'penality_after_tax' ,'advance_paid','payable_amount','total_amount'], 'number'],
            [['order_no', 'work_name', 'estimate_no', 'section_name', 'circle_name'], 'string', 'max' => 255],
            [['session'], 'string', 'max' => 7],
            [['billing_company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BillingCompany::className(), 'targetAttribute' => ['billing_company_id' => 'id']],
            [['billing_company_state'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['billing_company_state' => 'id']],
            [['billing_company_district'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\District::className(), 'targetAttribute' => ['billing_company_district' => 'id']],
            [['agreement_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Agreement::className(), 'targetAttribute' => ['agreement_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'agreement_id' => Yii::t('models', 'Agreement'),
            'invoice_no' => Yii::t('models', 'Invoice No'),
            'has_percentage' => Yii::t('models', 'Has Percentage'),
            'related_invoice' => Yii::t('models', 'Related Invoice'),
            'invoice_date' => Yii::t('models', 'Invoice Date'),
            'order_no' => Yii::t('models', 'Order No'),
            'work_name' => Yii::t('models', 'Work Name'),
            'estimate_no' => Yii::t('models', 'Particular'),
            'section_name' => Yii::t('models', 'Section Name'),
            'start_date' => Yii::t('models', 'Start Date'),
            'complete_date' => Yii::t('models', 'Complete Date'),
            'circle_name' => Yii::t('models', 'Circle Name'),
            'billing_company_id' => Yii::t('models', 'Ship to Billing Company'),
            'billing_company_state' => Yii::t('models', 'Ship to Billing State'),
            'billing_company_district' => Yii::t('models', 'Ship to Billing District'),
            'billing_company_gst' => Yii::t('models', 'Ship to Billing Gst'),
            'base_amount' => Yii::t('models', 'Base Amount'),
            'schedule' => Yii::t('models', 'Schedule'),
            'schedule_rate' => Yii::t('models', 'Schedule Rate'),
            'schedule_amount' => Yii::t('models', 'Schedule Amount'),
            'total_amount' => Yii::t('models', 'Total Amount'),
            'tax_amount' => Yii::t('models', 'Tax Amount'),
            'after_tax_total' => Yii::t('models', 'Payable Amount'),
            'penality_amount' => Yii::t('models', 'Penality Amount'),
            'stamp' => Yii::t('models', 'Stamp'),
            'penality_tax' => Yii::t('models', 'Penality Tax @ 18%'),
            'penality_after_tax' => Yii::t('models', 'Penality After Tax'),
            'advance_paid' => Yii::t('models', 'Advance Paid'),
            'payable_amount' => Yii::t('models', 'Payable Amount'),
            'tax_note' => Yii::t('models', 'Tax Note'),
            'deduction_note' => Yii::t('models', 'Deduction Note'),
            'company_id' => Yii::t('models', 'Company'),
            'session' => Yii::t('models', 'Session'),
            'status' => Yii::t('models', 'Status'),
            'has_credit_note' => Yii::t('models', 'Has Credit Note'),
            'credit_note_invoice_id' => Yii::t('models', 'Credit Note Bill No'),
            'mode_of_transport' => Yii::t('models', 'Mode Of Transport'),
            'transporter' => Yii::t('models', 'Transporter'),
            'gr_no' => Yii::t('models', 'GR/LR NO'),
            'vehicle_no' => Yii::t('models', 'Vehicle No'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreditNote()
    {
        return $this->hasOne(\app\models\AgreementBill::className(), ['id' => 'credit_note_invoice_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreement()
    {
        return $this->hasOne(\app\models\Agreement::className(), ['id' => 'agreement_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillDeductions()
    {
        return $this->hasMany(\app\models\BillDeduction::className(), ['invoice_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillItems()
    {
        return $this->hasMany(\app\models\BillItem::className(), ['invoice_id' => 'id'])->orderBy(['sno'=>SORT_ASC]);
    }

    public function getBillStatuses()
    {
        return $this->hasMany(\app\models\AgreementBillStatus::className(), ['bill_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillTaxes()
    {
        return $this->hasMany(\app\models\BillTax::className(), ['invoice_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillPenalties()
    {
        return $this->hasMany(\app\models\BillPenality::className(), ['invoice_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillBack()
    {
        return $this->hasMany(\app\models\AgreementBillBack::className(), ['agreement_id' => 'agreement_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillingCompany()
    {
        return $this->hasOne(\app\models\BillingCompany::className(), ['id' => 'billing_company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillingCompanyState()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'billing_company_state']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillingCompanyDistrict()
    {
        return $this->hasOne(\app\models\District::className(), ['id' => 'billing_company_district']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSignature()
    {
        return $this->hasOne(\app\models\SignatureMaster::className(), ['id' => 'stamp']);
    }
    
    public function getModeOfTransport()
    {
        return $this->hasOne(\app\models\ModeOfTransport::className(), ['id' => 'mode_of_transport']);
    }

}
