<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "agreement_vendor".
 *
 * @property integer $id
 * @property integer $agreement_id
 * @property string $vendor_name
 * @property string $vendor_code
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Agreement $agreement
 * @property \app\models\Company $company
 * @property string $aliasModel
 */
abstract class AgreementVendor extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'agreement_vendor';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['agreement_id', 'vendor_code', 'company_id', 'session','vendor_name'], 'required'],
            [['agreement_id', 'company_id'], 'integer'],
            [['vendor_code'], 'string', 'max' => 20],
            [['vendor_name'], 'string', 'max' => 255],
            [['session'], 'string', 'max' => 7],
            [['agreement_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Agreement::className(), 'targetAttribute' => ['agreement_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'agreement_id' => 'Agreement',
            'vendor_name' => 'Vendor Name',
            'vendor_code' => 'Vendor Code',
            'company_id' => 'Company',
            'session' => 'Session',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreement()
    {
        return $this->hasOne(\app\models\Agreement::className(), ['id' => 'agreement_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }




}
