<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "agreement_rate_schedule".
 *
 * @property integer $id
 * @property integer $agreement_id
 * @property integer $sno
 * @property string $type
 * @property string $item
 * @property string $hsn_no
 * @property integer $unit
 * @property string $quantity
 * @property string $rate
 * @property string $amount
 * @property integer $is_active
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Agreement $agreement
 * @property \app\models\BillItem $billItem
 * @property \app\models\Company $company
 * @property \app\models\Uom $unit
 * @property string $aliasModel
 */
abstract class AgreementRateSchedule extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'agreement_rate_schedule';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['agreement_id', 'item', 'hsn_no', 'unit', 'quantity', 'rate', 'company_id', 'session'], 'required'],
            [['agreement_id', 'unit', 'company_id','sno','is_active'], 'integer'],
            [['item','type'], 'string'],
            [['quantity', 'rate','amount'], 'number'],
            [['hsn_no'], 'string', 'max' => 6],
            [['session'], 'string', 'max' => 7],
            [['agreement_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Agreement::className(), 'targetAttribute' => ['agreement_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['unit'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Uom::className(), 'targetAttribute' => ['unit' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'agreement_id' => 'Agreement ID',
            'sno' => 'S. No.',
            'type' => 'Type',
            'item' => 'Item',
            'hsn_no' => 'Hsn No',
            'unit' => 'Unit',
            'quantity' => 'Quantity',
            'rate' => 'Rate',
            'amount' => 'Amount',
            'is_active' => 'New Rate',
            'company_id' => 'Company ID',
            'session' => 'Session',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreement()
    {
        return $this->hasOne(\app\models\Agreement::className(), ['id' => 'agreement_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUom()
    {
        return $this->hasOne(\app\models\Uom::className(), ['id' => 'unit']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillItem()
    {
        return $this->hasOne(\app\models\BillItem::className(), ['item' => 'id','agreement_id'=>'agreement_id']);
    }

}
