<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "agreement_gauranty_type".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \app\models\AgreementGauranty[] $agreementGauranties
 * @property string $aliasModel
 */
abstract class AgreementGaurantyType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'agreement_gauranty_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreementGauranties()
    {
        return $this->hasMany(\app\models\AgreementGauranty::className(), ['name' => 'id']);
    }




}
