<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "agreement".
 *
 * @property integer $id
 * @property integer $company_id
 * @property string $session
 * @property integer $file_no
 * @property string $agreement_no
 * @property string $agreement_name
 * @property integer $district_id
 * @property string $cost
 * @property string $date
 * @property string $expire_date
 * @property string $zone
 * @property integer $state_id
 * @property string $gst_no
 * @property integer $schedule
 * @property string $rate
 * @property integer $contract_company_id
 * @property integer $contract_company_state
 * @property integer $contract_company_district
 * @property string $contract_company_gst
 * @property integer $type
 * @property string $taxable_amount
 * @property string $tax_amount
 * @property string $payable_amount
 * @property integer $status
 * @property integer $bill_to_id
 * @property integer $bill_to_state
 * @property string $bill_to_gst
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\AgreementBill[] $agreementBills
 * @property \app\models\AgreementGauranty[] $agreementGauranties
 * @property \app\models\AgreementRateSchedule[] $agreementRateSchedule
 * @property \app\models\AgreementSites[] $agreementSites
 * @property \app\models\AgreementTax[] $agreementTaxes
 * @property \app\models\AgreementVendor[] $agreementVendors
 * @property \app\models\BillDeduction[] $billDeductions
 * @property \app\models\BillItem[] $billItems
 * @property \app\models\BillTax[] $billTaxes
 * @property \app\models\BillingCompany $billTo
 * @property \app\models\State $billToState
 * @property \app\models\District $district
 * @property \app\models\Company $company
 * @property \app\models\ContractCompany $contractCompany
 * @property \app\models\State $contractCompanyState
 * @property \app\models\District $contractCompanyDistrict
 * @property \app\models\State $state
 * @property \app\models\AgreementBillBack $billBack
 * @property string $aliasModel
 */
abstract class Agreement extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'agreement';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['company_id', 'session', 'agreement_no', 'cost', 'date', 'state_id', 'gst_no', 'contract_company_id', 'contract_company_state', 'contract_company_gst'], 'required'],
            [['company_id', 'file_no', 'state_id', 'schedule', 'contract_company_id', 'contract_company_state','contract_company_district', 'type', 'status', 'bill_to_id', 'bill_to_state'], 'integer'],
            [['cost', 'rate','taxable_amount','tax_amount','payable_amount'], 'number'],
            [['date', 'expire_date'], 'safe'],
            [['session'], 'string', 'max' => 7],
            [['agreement_no', 'zone', 'gst_no', 'contract_company_gst','agreement_name'], 'string', 'max' => 255],
            [['bill_to_gst'], 'string', 'max' => 30],
            [['bill_to_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BillingCompany::className(), 'targetAttribute' => ['bill_to_id' => 'id']],
            [['bill_to_state'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['bill_to_state' => 'id']],
            [['district_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\District::className(), 'targetAttribute' => ['district_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['contract_company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ContractCompany::className(), 'targetAttribute' => ['contract_company_id' => 'id']],
            [['contract_company_state'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['contract_company_state' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['state_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'company_id' => Yii::t('models', 'Company'),
            'session' => Yii::t('models', 'Session'),
            'file_no' => Yii::t('models', 'File No'),
            'agreement_no' => Yii::t('models', 'Agreement No'),
            'agreement_name' => Yii::t('models', 'Agreement Name'),
            'district_id' => Yii::t('models', 'District'),
            'cost' => Yii::t('models', 'Cost'),
            'date' => Yii::t('models', 'Date'),
            'expire_date' => Yii::t('models', 'Expire Date'),
            'zone' => Yii::t('models', 'Zone'),
            'state_id' => Yii::t('models', 'State'),
            'gst_no' => Yii::t('models', 'Gst No'),
            'schedule' => Yii::t('models', 'Schedule'),
            'rate' => Yii::t('models', 'Rate'),
            'contract_company_id' => Yii::t('models', 'Contract Company'),
            'contract_company_state' => Yii::t('models', 'Contract Company State'),
            'contract_company_district' => Yii::t('models', 'Contract Company District'),
            'contract_company_gst' => Yii::t('models', 'Contract Company Gst'),
            'type' => Yii::t('models', 'Type'),
            'taxable_amount' => Yii::t('models','Taxable Amount'),
            'tax_amount' => Yii::t('models','Tax Amount'),
            'payable_amount' => Yii::t('models','Payable Amount'),
            'status' => Yii::t('models', 'Status'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
            'bill_to_id' => Yii::t('models', 'Bill To ID'),
            'bill_to_state' => Yii::t('models', 'Bill To State'),
            'bill_to_gst' => Yii::t('models', 'Bill To Gst'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreementBills()
    {
        return $this->hasMany(\app\models\AgreementBill::className(), ['agreement_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreementGauranties()
    {
        return $this->hasMany(\app\models\AgreementGauranty::className(), ['agreement_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreementRateSchedule()
    {
        return $this->hasMany(\app\models\AgreementRateSchedule::className(), ['agreement_id' => 'id'])->orderBy(['sno'=>SORT_ASC]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreementSites()
    {
        return $this->hasMany(\app\models\AgreementSites::className(), ['agreement_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreementTaxes()
    {
        return $this->hasMany(\app\models\AgreementTax::className(), ['agreement_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreementVendors()
    {
        return $this->hasMany(\app\models\AgreementVendor::className(), ['agreement_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillDeductions()
    {
        return $this->hasMany(\app\models\BillDeduction::className(), ['agreement_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillItems()
    {
        return $this->hasMany(\app\models\BillItem::className(), ['agreement_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillTaxes()
    {
        return $this->hasMany(\app\models\BillTax::className(), ['agreement_id' => 'id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillBack()
    {
        return $this->hasMany(\app\models\AgreementBillBack::className(), ['agreement_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillTo()
    {
        return $this->hasOne(\app\models\BillingCompany::className(), ['id' => 'bill_to_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillToState()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'bill_to_state']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContractCompany()
    {
        return $this->hasOne(\app\models\ContractCompany::className(), ['id' => 'contract_company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContractCompanyState()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'contract_company_state']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContractCompanyDistrict()
    {
        return $this->hasOne(\app\models\District::className(), ['id' => 'contract_company_district']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'state_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrict()
    {
        return $this->hasOne(\app\models\District::className(), ['id' => 'district_id']);
    }




}
