<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "agreement_gauranty".
 *
 * @property integer $id
 * @property integer $agreement_id
 * @property integer $name
 * @property string $date
 * @property string $gauranty_no
 * @property string $amount
 * @property string $expire_date
 * @property string $refund_date
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Agreement $agreement
 * @property \app\models\Company $company
 * @property \app\models\AgreementGaurantyType $gaurantyType
 * @property string $aliasModel
 */
abstract class AgreementGauranty extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'agreement_gauranty';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['agreement_id', 'name', 'company_id'], 'integer'],
            [['date', 'expire_date', 'refund_date'], 'safe'],
            [['amount'], 'number'],
            [['gauranty_no'], 'string', 'max' => 20],
            [['session'], 'string', 'max' => 7],
            [['agreement_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Agreement::className(), 'targetAttribute' => ['agreement_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['name'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\AgreementGaurantyType::className(), 'targetAttribute' => ['name' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'agreement_id' => Yii::t('models', 'Agreement ID'),
            'name' => Yii::t('models', 'Name'),
            'date' => Yii::t('models', 'Date'),
            'gauranty_no' => Yii::t('models', 'Gauranty No'),
            'amount' => Yii::t('models', 'Amount'),
            'expire_date' => Yii::t('models', 'Expire Date'),
            'refund_date' => Yii::t('models', 'Refund Date'),
            'company_id' => Yii::t('models', 'Company ID'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreement()
    {
        return $this->hasOne(\app\models\Agreement::className(), ['id' => 'agreement_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGaurantyType()
    {
        return $this->hasOne(\app\models\AgreementGaurantyType::className(), ['id' => 'name']);
    }




}
