<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "bank_account".
 *
 * @property integer $id
 * @property string $bank_name
 * @property string $branch_name
 * @property string $account_no
 * @property string $ifsc_code
 * @property string $customer_name
 * @property string $openning_balance
 * @property integer $balance_type
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\AccountLedger[] $accountLedgers
 * @property \app\models\Company $company
 * @property string $aliasModel
 */
abstract class BankAccount extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bank_account';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['bank_name', 'account_no', 'company_id', 'session'], 'required'],
            [['openning_balance'], 'number'],
            [['balance_type', 'company_id'], 'integer'],
            [['bank_name', 'branch_name', 'account_no', 'customer_name'], 'string', 'max' => 255],
            [['ifsc_code'], 'string', 'max' => 12],
            [['session'], 'string', 'max' => 7],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'bank_name' => Yii::t('models', 'Bank Name'),
            'branch_name' => Yii::t('models', 'Branch Name'),
            'account_no' => Yii::t('models', 'Account No'),
            'ifsc_code' => Yii::t('models', 'Ifsc Code'),
            'customer_name' => Yii::t('models', 'Customer Name'),
            'openning_balance' => Yii::t('models', 'Openning Balance'),
            'balance_type' => Yii::t('models', 'Balance Type'),
            'company_id' => Yii::t('models', 'Company ID'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccountLedgers()
    {
        return $this->hasMany(\app\models\AccountLedger::className(), ['account' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }




}
