<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "bill_back_master".
 *
 * @property integer $id
 * @property integer $srmid
 * @property string $type
 * @property integer $sno
 * @property string $description
 * @property string $aliasModel
 */
abstract class BillBackMaster extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bill_back_master';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'sno', 'description'], 'required'],
            [['sno','srmid'], 'integer'],
            [['description'], 'string'],
            [['type'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'srmid' => 'Srmid',
            'type' => 'Type',
            'sno' => 'Sno',
            'description' => 'Description',
        ];
    }




}
