<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "bill_item".
 *
 * @property integer $id
 * @property integer $invoice_id
 * @property integer $agreement_id
 * @property integer $sno
 * @property string $item
 * @property string $hsn_no
 * @property string $gst
 * @property integer $unit
 * @property string $quantity
 * @property string $rate
 * @property string $percentage
 * @property string $base_amount
 * @property integer $tax_id
 * @property string $tax_rate
 * @property string $tax_amount
 * @property string $amount
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Agreement $agreement
 * @property \app\models\Company $company
 * @property \app\models\AgreementBill $invoice
 * @property \app\models\Uom $unitName
 * @property \app\models\AgreementRateSchedule $itemName
 * @property string $aliasModel
 */
abstract class BillItem extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bill_item';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'agreement_id', 'item', 'hsn_no', 'unit', 'rate', 'amount', 'company_id', 'session'], 'required'],
            [['invoice_id', 'agreement_id', 'unit', 'company_id','sno','tax_id'], 'integer'],
            [['gst', 'quantity', 'rate', 'amount','percentage','base_amount','tax_rate','tax_amount'], 'number'],
            [['hsn_no'], 'string', 'max' => 6],
            [['session'], 'string', 'max' => 7],
            [['item'], 'safe'],
            [['agreement_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Agreement::className(), 'targetAttribute' => ['agreement_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['invoice_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\AgreementBill::className(), 'targetAttribute' => ['invoice_id' => 'id']],
            [['unit'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Uom::className(), 'targetAttribute' => ['unit' => 'id']],
            [['tax_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Tax::className(), 'targetAttribute' => ['tax_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'invoice_id' => Yii::t('models', 'Invoice ID'),
            'agreement_id' => Yii::t('models', 'Agreement ID'),
            'sno' => Yii::t('models', 'S. No.'),
            'item' => Yii::t('models', 'Item'),
            'hsn_no' => Yii::t('models', 'Hsn No'),
            'gst' => Yii::t('models', 'Gst'),
            'unit' => Yii::t('models', 'Unit'),
            'quantity' => Yii::t('models', 'Quantity'),
            'rate' => Yii::t('models', 'Rate'),
            'percentage' => Yii::t('models', 'Percentage'),
            'amount' => Yii::t('models', 'Amount'),
            'company_id' => Yii::t('models', 'Company ID'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreement()
    {
        return $this->hasOne(\app\models\Agreement::className(), ['id' => 'agreement_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInvoice()
    {
        return $this->hasOne(\app\models\AgreementBill::className(), ['id' => 'invoice_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnitName()
    {
        return $this->hasOne(\app\models\Uom::className(), ['id' => 'unit']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemName()
    {
        return $this->hasOne(\app\models\AgreementRateSchedule::className(), ['id' => 'item']);
    }




}
