<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "bill_deduction".
 *
 * @property integer $id
 * @property integer $invoice_id
 * @property integer $agreement_id
 * @property integer $tax_id
 * @property integer $is_rate
 * @property string $rate
 * @property string $amount
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Agreement $agreement
 * @property \app\models\Company $company
 * @property \app\models\AgreementBill $invoice
 * @property \app\models\Tax $tax
 * @property string $aliasModel
 */
abstract class BillDeduction extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bill_deduction';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['invoice_id', 'agreement_id', 'tax_id', 'amount', 'company_id', 'session'], 'required'],
            [['invoice_id', 'agreement_id', 'tax_id', 'company_id','is_rate'], 'integer'],
            [['rate', 'amount'], 'number'],
            [['session'], 'string', 'max' => 7],
            [['agreement_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Agreement::className(), 'targetAttribute' => ['agreement_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['invoice_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\AgreementBill::className(), 'targetAttribute' => ['invoice_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'invoice_id' => Yii::t('models', 'Invoice ID'),
            'agreement_id' => Yii::t('models', 'Agreement ID'),
            'tax_id' => Yii::t('models', 'Tax ID'),
            'is_rate' => Yii::t('models', 'Use Rate'),
            'rate' => Yii::t('models', 'Rate'),
            'amount' => Yii::t('models', 'Amount'),
            'company_id' => Yii::t('models', 'Company ID'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgreement()
    {
        return $this->hasOne(\app\models\Agreement::className(), ['id' => 'agreement_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInvoice()
    {
        return $this->hasOne(\app\models\AgreementBill::className(), ['id' => 'invoice_id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTax()
    {
        return $this->hasOne(\app\models\Tax::className(), ['id' => 'tax_id']);
    }



}
