<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "billing_company".
 *
 * @property integer $id
 * @property string $name
 * @property \app\models\BillingCompanyGst $billingCompanyGst
 * @property string $aliasModel
 */
abstract class BillingCompany extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'billing_company';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
        ];
    }


    public function getBillingCompanyGst()
    {
        return $this->hasMany(\app\models\BillingCompanyGst::className(), ['company_id' => 'id']);
    }



}
