<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "company".
 *
 * @property integer $id
 * @property string $name
 * @property string $name_color
 * @property integer $type
 * @property string $address
 * @property string $address_color
 * @property integer $state
 * @property integer $district
 * @property string $pincode
 * @property string $person
 * @property string $number
 * @property string $email
 * @property string $pancard_no
 * @property string $gst_no
 * @property string $logo
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\District $districtName
 * @property \app\models\State $stateName
 * @property \app\models\CompanyType $companyType
 * @property \app\models\CompanyGst $companyGst
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class Company extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'company';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'type', 'address', 'state', 'district', 'pincode', 'person', 'number', 'email', 'pancard_no', 'gst_no'], 'required'],
            [['type', 'state', 'district'], 'integer'],
            [['address','name_color','address_color'], 'string'],
            [['name', 'person', 'email', 'pancard_no', 'gst_no','logo'], 'string', 'max' => 255],
            [['pincode'], 'string', 'max' => 6],
            [['number'], 'string', 'max' => 12],
            [['district'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\District::className(), 'targetAttribute' => ['district' => 'id']],
            [['state'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['state' => 'id']],
            [['type'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CompanyType::className(), 'targetAttribute' => ['type' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'name_color' => Yii::t('models', 'Color'),
            'type' => Yii::t('models', 'Type'),
            'address' => Yii::t('models', 'Address'),
            'address_color' => Yii::t('models', 'Color'),
            'state' => Yii::t('models', 'State'),
            'district' => Yii::t('models', 'District'),
            'pincode' => Yii::t('models', 'Pincode'),
            'person' => Yii::t('models', 'Person'),
            'number' => Yii::t('models', 'Number'),
            'email' => Yii::t('models', 'Email'),
            'pancard_no' => Yii::t('models', 'Pancard No'),
            'gst_no' => Yii::t('models', 'Gst No'),
            'logo' => Yii::t('models', 'Logo'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrictName()
    {
        return $this->hasOne(\app\models\District::className(), ['id' => 'district']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStateName()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'state']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompanyType()
    {
        return $this->hasOne(\app\models\CompanyType::className(), ['id' => 'type']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'created_by']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'created_by']);
    }

    public function getCompanyGst()
    {
        return $this->hasMany(\app\models\CompanyGst::className(), ['company_id' => 'id']);
    }




}
