<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "company_addresses".
 *
 * @property integer $id
 * @property integer $type
 * @property integer $type_id
 * @property integer $district_id
 * @property string $legal_name
 * @property string $trade_name
 * @property string $address_1
 * @property string $address_2
 * @property string $location
 * @property string $pincode
 * @property string $phone
 * @property string $email
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\User $createdBy
 * @property \app\models\District $district
 * @property \app\models\User $updatedBy
 * @property string $aliasModel
 */
abstract class CompanyAddresses extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'company_addresses';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'type_id', 'district_id'], 'integer'],
            [['type_id', 'district_id', 'legal_name', 'address_1', 'location', 'pincode'], 'required'],
            [['legal_name', 'trade_name', 'address_1', 'address_2', 'location', 'email'], 'string', 'max' => 100],
            [['pincode'], 'string', 'max' => 6],
            [['phone'], 'string', 'max' => 12],
            ['district_id','unique', 'targetAttribute' => ['type', 'type_id','district_id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::class, 'targetAttribute' => ['created_by' => 'id']],
            [['district_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\District::class, 'targetAttribute' => ['district_id' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::class, 'targetAttribute' => ['updated_by' => 'id']],
            [['pincode'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pincodes::class, 'targetAttribute' => ['pincode' => 'pincode']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'type_id' => 'Type ID',
            'district_id' => 'District ID',
            'legal_name' => 'Legal Name',
            'trade_name' => 'Trade Name',
            'address_1' => 'Address 1',
            'address_2' => 'Address 2',
            'location' => 'Location',
            'pincode' => 'Pincode',
            'phone' => 'Phone',
            'email' => 'Email',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrict()
    {
        return $this->hasOne(\app\models\District::class, ['id' => 'district_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'updated_by']);
    }




}
