<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "contract_company_gst".
 *
 * @property integer $id
 * @property integer $company_id
 * @property integer $state_id
 * @property string $districts
 * @property string $gst_no
 *
 * @property \app\models\ContractCompany $company
 * @property \app\models\State $state
 * @property string $aliasModel
 */
abstract class ContractCompanyGst extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'contract_company_gst';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['company_id', 'state_id', 'gst_no','districts'], 'required'],
            [['company_id', 'state_id'], 'integer'],
            [['gst_no'], 'string', 'max' => 20],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ContractCompany::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['state_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'company_id' => Yii::t('models', 'Company'),
            'state_id' => Yii::t('models', 'State'),
            'districts' => Yii::t('models', 'Districts'),
            'gst_no' => Yii::t('models', 'Gst No'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\ContractCompany::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'state_id']);
    }




}
