<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "contract_company".
 *
 * @property integer $id
 * @property integer $company_id
 * @property string $name
 * @property \app\models\ContractCompanyGst $contractCompanyGst
 * @property \app\models\Sites $sites
 * @property \app\models\Company $company
 * @property string $aliasModel
 */
abstract class ContractCompany extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'contract_company';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name','company_id'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'company_id' => Yii::t('models', 'Company'),
        ];
    }

    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }
    
    public function getContractCompanyGst()
    {
        return $this->hasMany(\app\models\ContractCompanyGst::className(), ['company_id' => 'id']);
    }

    public function getSites()
    {
        return $this->hasMany(\app\models\Sites::className(), ['company_id' => 'id']);
    }




}
