<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "deduction_master".
 *
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property string $rate
 * @property integer deduction_type
 * @property integer $status
 * @property string $aliasModel
 */
abstract class DeductionMaster extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'deduction_master';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'type','deduction_type'], 'required'],
            [['rate'], 'number'],
            [['status'], 'integer'],
            [['name', 'type'], 'string', 'max' => 255],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'type' => Yii::t('models', 'Type'),
            'Deduction Type' => Yii::t('models', 'Deduction Type'),
            'rate' => Yii::t('models', 'Rate'),
            'status' => Yii::t('models', 'Status'),
        ];
    }




}
