<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "district".
 *
 * @property integer $id
 * @property string $district
 * @property integer $state_id
 *
 * @property \app\models\State $state
 * @property string $aliasModel
 */
abstract class District extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'district';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['district', 'state_id'], 'required'],
            [['state_id'], 'integer'],
            [['district'], 'string', 'max' => 100],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['state_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'district' => Yii::t('models', 'District'),
            'state_id' => Yii::t('models', 'State ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'state_id']);
    }




}
