<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "document".
 *
 * @property integer $id
 * @property string $name
 * @property string $file
 * @property integer $employee_id
 * @property integer $vendor_id
 * @property integer $worker_id
 * @property integer $worker_vendor_id
 * @property integer $site_dues_id
 * @property integer $company_dues_id
 * @property integer $status
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Employee $employee
 * @property \app\models\Vendor $vendor
 * @property \app\models\Worker $worker
 * @property \app\models\WorkerVendor $workerVendor
 * @property \app\models\SiteDues $siteDues
 * @property \app\models\CompanyDues $companyDues
 * @property string $aliasModel
 */
abstract class Document extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'document';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'file'], 'required'],
            [['employee_id', 'vendor_id', 'worker_id', 'worker_vendor_id', 'site_dues_id', 'company_dues_id', 'status'], 'integer'],
            [['name', 'file'], 'string', 'max' => 255],
            [['employee_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Employee::className(), 'targetAttribute' => ['employee_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Vendor::className(), 'targetAttribute' => ['vendor_id' => 'id']],
            [['worker_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Worker::className(), 'targetAttribute' => ['worker_id' => 'id']],
            [['worker_vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WorkerVendor::className(), 'targetAttribute' => ['worker_vendor_id' => 'id']],
            [['site_dues_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\SiteDues::className(), 'targetAttribute' => ['site_dues_id' => 'id']],
            [['company_dues_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CompanyDues::className(), 'targetAttribute' => ['company_dues_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'file' => 'File',
            'employee_id' => 'Employee',
            'vendor_id' => 'Vendor',
            'worker_id' => 'Worker',
            'worker_vendor_id' => 'Worker Vendor',
            'site_dues_id' => 'Site Dues',
            'company_dues_id' => 'Company Dues',
            'status' => 'Status',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployee()
    {
        return $this->hasOne(\app\models\Employee::className(), ['id' => 'employee_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Vendor::className(), ['id' => 'vendor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorker()
    {
        return $this->hasOne(\app\models\Worker::className(), ['id' => 'worker_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkerVendor()
    {
        return $this->hasOne(\app\models\WorkerVendor::className(), ['id' => 'worker_vendor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteDues()
    {
        return $this->hasOne(\app\models\SiteDues::className(), ['id' => 'site_dues_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompanyDues()
    {
        return $this->hasOne(\app\models\CompanyDues::className(), ['id' => 'company_dues_id']);
    }




}
