<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "einvoice_auth".
 *
 * @property integer $id
 * @property string $ClientId
 * @property string $UserName
 * @property string $AuthToken
 * @property string $Sek
 * @property string $TokenExpiry
 * @property string $aliasModel
 */
abstract class EinvoiceAuth extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'einvoice_auth';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ClientId', 'UserName', 'AuthToken', 'Sek', 'TokenExpiry'], 'required'],
            [['Sek'], 'string'],
            [['TokenExpiry'], 'safe'],
            [['ClientId', 'UserName', 'AuthToken'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ClientId' => 'Client ID',
            'UserName' => 'User Name',
            'AuthToken' => 'Auth Token',
            'Sek' => 'Sek',
            'TokenExpiry' => 'Token Expiry',
        ];
    }




}
