<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "einvoice".
 *
 * @property integer $id
 * @property string $DocNo
 * @property string $DocDt
 * @property string $AckNo
 * @property string $AckDt
 * @property string $Irn
 * @property string $SignedInvoice
 * @property string $SignedQRCode
 * @property string $Status
 * @property string $EwbNo
 * @property string $EwbDt
 * @property string $EwbValidTill
 * @property string $Remarks
 * @property integer $created_at
 * @property integer $created_by
 * @property string $aliasModel
 */
abstract class Einvoice extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'einvoice';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['DocNo', 'DocDt', 'AckNo', 'AckDt', 'Irn', 'SignedInvoice', 'SignedQRCode', 'Status'], 'required'],
            [['DocDt', 'AckDt', 'EwbDt', 'EwbValidTill'], 'safe'],
            [['SignedInvoice', 'SignedQRCode', 'Remarks'], 'string'],
            [['DocNo', 'AckNo'], 'string', 'max' => 50],
            [['Irn', 'EwbNo'], 'string', 'max' => 255],
            [['Status'], 'string', 'max' => 10]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'DocNo' => 'Doc No',
            'DocDt' => 'Doc Dt',
            'AckNo' => 'Ack No',
            'AckDt' => 'Ack Dt',
            'Irn' => 'Irn',
            'SignedInvoice' => 'Signed Invoice',
            'SignedQRCode' => 'Signed Qr Code',
            'Status' => 'Status',
            'EwbNo' => 'Ewb No',
            'EwbDt' => 'Ewb Dt',
            'EwbValidTill' => 'Ewb Valid Till',
            'Remarks' => 'Remarks',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
        ];
    }




}
