<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "employee_allowance".
 *
 * @property integer $id
 * @property integer $employee_id
 * @property integer $allowance_id
 * @property string $value
 *
 * @property \app\models\AllowanceMaster $allowance
 * @property \app\models\Employee $employee
 * @property string $aliasModel
 */
abstract class EmployeeAllowance extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'employee_allowance';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['allowance_id'], 'required'],
            [['employee_id', 'allowance_id'], 'integer'],
            [['value'], 'number'],
            [['allowance_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\AllowanceMaster::className(), 'targetAttribute' => ['allowance_id' => 'id']],
            [['employee_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Employee::className(), 'targetAttribute' => ['employee_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'employee_id' => Yii::t('models', 'Employee'),
            'allowance_id' => Yii::t('models', 'Allowance'),
            'value' => Yii::t('models', 'Value'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAllowance()
    {
        return $this->hasOne(\app\models\AllowanceMaster::className(), ['id' => 'allowance_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployee()
    {
        return $this->hasOne(\app\models\Employee::className(), ['id' => 'employee_id']);
    }




}
