<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "employee_extra_salary".
 *
 * @property integer $id
 * @property integer $employee_id
 * @property string $month
 * @property integer $days
 * @property string $salary
 * @property string $allowance
 * @property string $salary_with_allowance
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Company $company
 * @property \app\models\User $createdBy
 * @property \app\models\Employee $employee
 * @property \app\models\EmployeeExtraSalaryAllowance[] $employeeExtraSalaryAllowances
 * @property \app\models\User $updatedBy
 * @property string $aliasModel
 */
abstract class EmployeeExtraSalary extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'employee_extra_salary';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['employee_id', 'month', 'days', 'salary', 'salary_with_allowance', 'company_id', 'session'], 'required'],
            [['employee_id', 'days', 'company_id'], 'integer'],
            [['month'], 'safe'],
            [['salary', 'allowance', 'salary_with_allowance'], 'number'],
            [['session'], 'string', 'max' => 8],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['employee_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Employee::className(), 'targetAttribute' => ['employee_id' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['updated_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'employee_id' => Yii::t('models', 'Employee ID'),
            'month' => Yii::t('models', 'Month'),
            'days' => Yii::t('models', 'Days'),
            'salary' => Yii::t('models', 'Salary'),
            'allowance' => Yii::t('models', 'Allowance'),
            'salary_with_allowance' => Yii::t('models', 'Salary With Allowance'),
            'company_id' => Yii::t('models', 'Company ID'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployee()
    {
        return $this->hasOne(\app\models\Employee::className(), ['id' => 'employee_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployeeExtraSalaryAllowances()
    {
        return $this->hasMany(\app\models\EmployeeExtraSalaryAllowance::className(), ['salary_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'updated_by']);
    }




}
