<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "employee_extra_salary_allowance".
 *
 * @property integer $id
 * @property integer $employee_id
 * @property integer $salary_id
 * @property integer $allowance_id
 * @property string $amount
 *
 * @property \app\models\AllowanceMaster $allowance
 * @property \app\models\Employee $employee
 * @property \app\models\EmployeeExtraSalary $salary
 * @property string $aliasModel
 */
abstract class EmployeeExtraSalaryAllowance extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'employee_extra_salary_allowance';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['employee_id', 'salary_id', 'allowance_id', 'amount'], 'required'],
            [['employee_id', 'salary_id', 'allowance_id'], 'integer'],
            [['amount'], 'number'],
            [['allowance_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\AllowanceMaster::className(), 'targetAttribute' => ['allowance_id' => 'id']],
            [['employee_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Employee::className(), 'targetAttribute' => ['employee_id' => 'id']],
            [['salary_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\EmployeeExtraSalary::className(), 'targetAttribute' => ['salary_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'employee_id' => Yii::t('models', 'Employee ID'),
            'salary_id' => Yii::t('models', 'Salary ID'),
            'allowance_id' => Yii::t('models', 'Allowance ID'),
            'amount' => Yii::t('models', 'Amount'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAllowance()
    {
        return $this->hasOne(\app\models\AllowanceMaster::className(), ['id' => 'allowance_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployee()
    {
        return $this->hasOne(\app\models\Employee::className(), ['id' => 'employee_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSalary()
    {
        return $this->hasOne(\app\models\EmployeeExtraSalary::className(), ['id' => 'salary_id']);
    }




}
