<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "employee".
 *
 * @property integer $id
 * @property integer $emp_code
 * @property integer $user_id
 * @property string $emp_name
 * @property string $father_name
 * @property integer $emp_company
 * @property string $address
 * @property integer $state_id
 * @property integer $district_id
 * @property string $pincode
 * @property string $email
 * @property string $mobile
 * @property string $dob
 * @property string $joining_date
 * @property string $end_date
 * @property integer $designation
 * @property integer $is_deduction
 * @property integer $is_esi
 * @property string $salary
 * @property integer $fixed_leave
 * @property string $leaves
 * @property string $refference
 * @property string $aadhar
 * @property string $pancard
 * @property string $expense_balance
 * @property integer $expense_type
 * @property string $personal_balance
 * @property integer $personal_type
 * @property string $epf_no
 * @property string $esi_no
 * @property integer $status
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Designation $designationName
 * @property \app\models\District $district
 * @property \app\models\Company $empCompany
 * @property \app\models\State $state
 * @property \app\models\Document $document 
 * @property \app\models\Account $account
 * @property \app\models\Permission $permission
 * @property \app\models\EmployeeAllowance $allowances
 * @property string $aliasModel
 */
abstract class Employee extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'employee';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_code', 'emp_name', 'father_name', 'emp_company', 'address', 'state_id', 'district_id', 'pincode', 'designation', 'session','email','status'], 'required'],
            [['emp_code', 'user_id', 'emp_company', 'state_id', 'district_id', 'designation', 'expense_type', 'personal_type', 'status','is_deduction','fixed_leave','is_esi'], 'integer'],
            [['dob', 'joining_date','salary','leaves','end_date'], 'safe'],
            [['email'], 'unique'],
            [['expense_balance', 'personal_balance'], 'number'],
            [['emp_name', 'father_name', 'address', 'email', 'mobile', 'refference', 'aadhar', 'pancard','epf_no','esi_no'], 'string', 'max' => 255],
            [['pincode'], 'string', 'max' => 6],
            [['session'], 'string', 'max' => 7],
            [['designation'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Designation::className(), 'targetAttribute' => ['designation' => 'id']],
            [['district_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\District::className(), 'targetAttribute' => ['district_id' => 'id']],
            [['emp_company'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['emp_company' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['state_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'emp_code' => Yii::t('models', 'Code'),
            'user_id' => Yii::t('models', 'User ID'),
            'emp_name' => Yii::t('models', 'Name'),
            'father_name' => Yii::t('models', 'Father Name'),
            'emp_company' => Yii::t('models', 'Company'),
            'address' => Yii::t('models', 'Address'),
            'state_id' => Yii::t('models', 'State'),
            'district_id' => Yii::t('models', 'District'),
            'pincode' => Yii::t('models', 'Pincode'),
            'email' => Yii::t('models', 'Email'),
            'mobile' => Yii::t('models', 'Mobile'),
            'dob' => Yii::t('models', 'Dob'),
            'joining_date' => Yii::t('models', 'Joining Date'),
            'designation' => Yii::t('models', 'Designation'),
            'salary' => Yii::t('models', 'Salary'),
            'id_deduction' => Yii::t('models', 'Salary Deduction'),
            'id_esi' => Yii::t('models', 'ESI'),
            'refference' => Yii::t('models', 'Refference'),
            'aadhar' => Yii::t('models', 'Aadhar'),
            'fixed_leave' => Yii::t('models', 'Fixed Leave'),
            'pancard' => Yii::t('models', 'Pancard'),
            'expense_balance' => Yii::t('models', 'Expense Balance'),
            'expense_type' => Yii::t('models', 'Expense Type'),
            'personal_balance' => Yii::t('models', 'Personal Balance'),
            'personal_type' => Yii::t('models', 'Personal Type'),
            'epf_no' => Yii::t('models', 'EPF No'),
            'esi_no' => Yii::t('models', 'ESI No'),
            'status' => Yii::t('models', 'Status'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDesignationName()
    {
        return $this->hasOne(\app\models\Designation::className(), ['id' => 'designation']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrict()
    {
        return $this->hasOne(\app\models\District::className(), ['id' => 'district_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'emp_company']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'state_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocument()
    {
        return $this->hasMany(\app\models\Document::className(), ['employee_id' => 'id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccount()
    {
        return $this->hasMany(\app\models\Account::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPermission()
    {
        return $this->hasMany(\app\models\Permission::className(), ['user_id' => 'user_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAllowances()
    {
        return $this->hasMany(\app\models\EmployeeAllowance::className(), ['employee_id' => 'id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSalaryAllowance()
    {
        return $this->hasMany(\app\models\EmployeeSalaryAllowance::className(), ['employee_id' => 'id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSalaryDeduction()
    {
        return $this->hasMany(\app\models\EmployeeSalaryDeduction::className(), ['employee_id' => 'id']);
    }

}
