<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "employee_salary_deduction".
 *
 * @property integer $id
 * @property integer $employee_id
 * @property integer $salary_id
 * @property integer $deduction_id
 * @property integer $type
 * @property string $rate
 * @property string $amount
 *
 * @property \app\models\Employee $employee
 * @property \app\models\EmployeeSalary $salary
 * @property \app\models\DeductionMaster $deduction
 * @property string $aliasModel
 */
abstract class EmployeeSalaryDeduction extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'employee_salary_deduction';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['employee_id', 'salary_id', 'deduction_id'], 'required'],
            [['employee_id', 'salary_id', 'deduction_id','type'], 'integer'],
            [['rate', 'amount'], 'number'],
            [['employee_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Employee::className(), 'targetAttribute' => ['employee_id' => 'id']],
            [['salary_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\EmployeeSalary::className(), 'targetAttribute' => ['salary_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'employee_id' => Yii::t('models', 'Employee'),
            'salary_id' => Yii::t('models', 'Salary'),
            'type' => Yii::t('models', 'Type'),
            'deduction_id' => Yii::t('models', 'Deduction'),
            'rate' => Yii::t('models', 'Rate'),
            'amount' => Yii::t('models', 'Amount'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployee()
    {
        return $this->hasOne(\app\models\Employee::className(), ['id' => 'employee_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSalary()
    {
        return $this->hasOne(\app\models\EmployeeSalary::className(), ['id' => 'salary_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getdeduction()
    {
        return $this->hasOne(\app\models\DeductionMaster::className(), ['id' => 'deduction_id']);
    }
    
}
