<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "erp_modules".
 *
 * @property integer $id
 * @property string $modules
 * @property string $aliasModel
 */
abstract class ErpModules extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'erp_modules';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['modules'], 'required'],
            [['modules'], 'string', 'max' => 255],
            [['modules'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'modules' => 'Modules',
        ];
    }




}
