<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "history".
 *
 * @property integer $id
 * @property string $model_name
 * @property integer $model_id
 * @property string $other_id
 * @property integer $action_status
 * @property string $meta_label
 * @property string $meta
 * @property integer $seen_status
 * @property integer $flush_status
 * @property integer $created_at
 * @property integer $created_by
 *
 * @property \app\models\User $createdBy
 * @property string $aliasModel
 */
abstract class History extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'history';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['model_name', 'model_id', 'action_status'], 'required'],
            [['model_id', 'action_status', 'seen_status', 'flush_status'], 'integer'],
            [['meta'], 'string'],
            [['model_name'], 'string', 'max' => 100],
            [['other_id'], 'string', 'max' => 50],
            [['meta_label'], 'string', 'max' => 255],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['created_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'model_name' => Yii::t('models', 'Model Name'),
            'model_id' => Yii::t('models', 'Model ID'),
            'other_id' => Yii::t('models', 'Other ID'),
            'action_status' => Yii::t('models', 'Action Status'),
            'meta_label' => Yii::t('models', 'Meta Label'),
            'meta' => Yii::t('models', 'Meta'),
            'seen_status' => Yii::t('models', 'Seen Status'),
            'flush_status' => Yii::t('models', 'Flush Status'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'seen_status' => Yii::t('models', '1->Unseen,2->Seen'),
            'flush_status' => Yii::t('models', '1->NO,2->yes'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'created_by']);
    }




}
