<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "payment".
 *
 * @property integer $id
 * @property string $ref_no
 * @property string $date
 * @property integer $contract_company_id
 * @property integer $state
 * @property integer $district_id
 * @property integer $site_id
 * @property integer $from_head
 * @property string $from_account
 * @property integer $to_head
 * @property string $particular
 * @property string $to_account
 * @property string $amount
 * @property string $tds_rate
 * @property string $tds_amount
 * @property string $net_amount
 * @property integer $status
 * @property integer $company_id
 * @property integer $to_company
 * @property integer $worker_vendor
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Company $company
 * @property \app\models\Company $toCompany
 * @property \app\models\District $district
 * @property \app\models\Ledger[] $ledgers
 * @property \app\models\Sites $site
 * @property \app\models\ContractCompany $contractCompany
 * @property \app\models\State $state
 * @property string $aliasModel
 */
abstract class Payment extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'payment';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date', 'district_id', 'site_id', 'from_head', 'from_account', 'to_head', 'particular', 'to_account', 'company_id','to_company', 'session'], 'required'],
            [['date'], 'safe'],
            [['district_id', 'site_id', 'from_head', 'to_head', 'status', 'company_id','worker_vendor','to_company'], 'integer'],
            [['particular'], 'string'],
            [['amount', 'tds_rate', 'tds_amount', 'net_amount'], 'number'],
            [['ref_no'], 'string', 'max' => 30],
            [['from_account', 'to_account'], 'string', 'max' => 255],
            [['session'], 'string', 'max' => 7],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['to_company'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['to_company' => 'id']],
            [['district_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\District::className(), 'targetAttribute' => ['district_id' => 'id']],
            [['site_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Sites::className(), 'targetAttribute' => ['site_id' => 'id']],
            [['contract_company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ContractCompany::className(), 'targetAttribute' => ['contract_company_id' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['state_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'ref_no' => Yii::t('models', 'Ref No'),
            'date' => Yii::t('models', 'Date'),
            'contract_company_id' => Yii::t('models', 'Contract Company'),
            'state_id' => Yii::t('models', 'State'),
            'district_id' => Yii::t('models', 'District'),
            'site_id' => Yii::t('models', 'Site'),
            'from_head' => Yii::t('models', 'From Head'),
            'from_account' => Yii::t('models', 'From Account'),
            'to_head' => Yii::t('models', 'To Head'),
            'particular' => Yii::t('models', 'Particular'),
            'to_account' => Yii::t('models', 'To Account'),
            'amount' => Yii::t('models', 'Amount'),
            'tds_rate' => Yii::t('models', 'Tds Rate'),
            'tds_amount' => Yii::t('models', 'Tds Amount'),
            'net_amount' => Yii::t('models', 'Net Amount'),
            'status' => Yii::t('models', 'Status'),
            'company_id' => Yii::t('models', 'Company'),
            'to_company' => Yii::t('models', 'Company'),
            'worker_vendor' => Yii::t('models', 'Worker Vendor'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getToCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'to_company']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrict()
    {
        return $this->hasOne(\app\models\District::className(), ['id' => 'district_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLedgers()
    {
        return $this->hasMany(\app\models\Ledger::className(), ['transaction_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSite()
    {
        return $this->hasOne(\app\models\Sites::className(), ['id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContractCompany()
    {
        return $this->hasOne(\app\models\ContractCompany::className(), ['id' => 'contract_company_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'state_id']);
    }



}
