<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "permission".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $controller
 * @property string $action
 *
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class Permission extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'permission';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'controller'], 'required'],
            [['user_id'], 'integer'],
            [['action'], 'safe'],
            [['controller'], 'string', 'max' => 255],
            [['user_id', 'controller'], 'unique', 'targetAttribute' => ['user_id', 'controller']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'controller' => 'Controller',
            'action' => 'Action',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }




}
