<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pincodes".
 *
 * @property integer $id
 * @property integer $state_id
 * @property string $pincode
 *
 * @property \app\models\State $state
 * @property string $aliasModel
 */
abstract class Pincodes extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pincodes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['state_id', 'pincode'], 'required'],
            [['state_id'], 'integer'],
            [['pincode'], 'string', 'max' => 6],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::class, 'targetAttribute' => ['state_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'state_id' => 'State ID',
            'pincode' => 'Pincode',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\app\models\State::class, ['id' => 'state_id']);
    }




}
