<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "purchase_bill".
 *
 * @property integer $id
 * @property string $name
 * @property string $gstin
 * @property string $invoice_no
 * @property string $date
 * @property string $amount
 * @property string $tax
 * @property string $total
 * @property string $file
 * @property integer $status
 * @property integer $company_id
 * @property integer $state_id
 * @property string $company_gstin
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Company $company
 * @property \app\models\User $createdBy
 * @property \app\models\PurchaseBillItems[] $purchaseBillItems
 * @property \app\models\State $state
 * @property \app\models\User $updatedBy
 * @property string $aliasModel
 */
abstract class PurchaseBill extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchase_bill';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'gstin', 'state_id'], 'required'],
            [['date'], 'safe'],
            [['amount', 'tax', 'total'], 'number'],
            [['status', 'company_id', 'state_id'], 'integer'],
            [['name', 'file'], 'string', 'max' => 255],
            [['gstin'], 'string', 'max' => 16],
            [['invoice_no'], 'string', 'max' => 30],
            [['company_gstin'], 'string', 'max' => 20],
            [['session'], 'string', 'max' => 8],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['state_id' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['updated_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Billing Company Name'),
            'gstin' => Yii::t('models', 'Billing Company Gst No'),
            'invoice_no' => Yii::t('models', 'Invoice No'),
            'date' => Yii::t('models', 'Date'),
            'amount' => Yii::t('models', 'Amount'),
            'tax' => Yii::t('models', 'Tax'),
            'total' => Yii::t('models', 'Total'),
            'file' => Yii::t('models', 'File'),
            'status' => Yii::t('models', 'Status'),
            'company_id' => Yii::t('models', 'Company'),
            'state_id' => Yii::t('models', 'State'),
            'company_gstin' => Yii::t('models', 'Company Gst No'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchaseBillItems()
    {
        return $this->hasMany(\app\models\PurchaseBillItems::className(), ['purchase_bill_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'state_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'updated_by']);
    }




}
