<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "purchase_product_items".
 *
 * @property integer $id
 * @property integer $purchase_product_id
 * @property integer $store_products_id
 * @property integer $uom_id
 * @property integer $quantity
 * @property integer $status
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\User $createdBy
 * @property \app\models\PurchaseProduct $purchaseProduct
 * @property \app\models\StoreProducts $storeProducts
 * @property \app\models\Uom $uom
 * @property \app\models\User $updatedBy
 * @property string $aliasModel
 */
abstract class PurchaseProductItems extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchase_product_items';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'store_products_id', 'uom_id', 'quantity'], 'required'],
            [['purchase_product_id', 'store_products_id', 'uom_id', 'quantity', 'status'], 'integer'],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::class, 'targetAttribute' => ['created_by' => 'id']],
            [['purchase_product_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PurchaseProduct::class, 'targetAttribute' => ['purchase_product_id' => 'id']],
            [['store_products_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StoreProducts::class, 'targetAttribute' => ['store_products_id' => 'id']],
            [['uom_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Uom::class, 'targetAttribute' => ['uom_id' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::class, 'targetAttribute' => ['updated_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'purchase_product_id' => 'Purchase Product',
            'store_products_id' => 'Store Products',
            'uom_id' => 'Uom',
            'quantity' => 'Quantity',
            'status' => 'Status',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchaseProduct()
    {
        return $this->hasOne(\app\models\PurchaseProduct::class, ['id' => 'purchase_product_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStoreProducts()
    {
        return $this->hasOne(\app\models\StoreProducts::class, ['id' => 'store_products_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUom()
    {
        return $this->hasOne(\app\models\Uom::class, ['id' => 'uom_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'updated_by']);
    }




}
