<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "purchase_bill_items".
 *
 * @property integer $id
 * @property integer $purchase_bill_id
 * @property string $particular
 * @property string $hsn_no
 * @property string $rate
 * @property string $quantity
 * @property string $amount
 * @property string $total
 *
 * @property \app\models\PurchaseBill $purchaseBill
 * @property \app\models\PurchaseBillItemsTax[] $purchaseBillItemsTaxes
 * @property string $aliasModel
 */
abstract class PurchaseBillItems extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchase_bill_items';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['purchase_bill_id', 'particular', 'rate', 'quantity'], 'required'],
            [['purchase_bill_id'], 'integer'],
            [['particular'], 'string'],
            [['rate', 'amount', 'total','quantity'], 'number'],
            [['hsn_no'], 'string', 'max' => 10],
            [['purchase_bill_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PurchaseBill::className(), 'targetAttribute' => ['purchase_bill_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'purchase_bill_id' => Yii::t('models', 'Purchase Bill ID'),
            'particular' => Yii::t('models', 'Particular'),
            'hsn_no' => Yii::t('models', 'Hsn No'),
            'rate' => Yii::t('models', 'Rate'),
            'quantity' => Yii::t('models', 'Quantity'),
            'amount' => Yii::t('models', 'Amount'),
            'total' => Yii::t('models', 'Total'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchaseBill()
    {
        return $this->hasOne(\app\models\PurchaseBill::className(), ['id' => 'purchase_bill_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchaseBillItemsTaxes()
    {
        return $this->hasMany(\app\models\PurchaseBillItemsTax::className(), ['purchase_bill_items_id' => 'id']);
    }




}
