<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "purchase_bill_items_tax".
 *
 * @property integer $id
 * @property integer $purchase_bill_items_id
 * @property integer $tax_id
 * @property string $rate
 * @property string $tax_amount
 *
 * @property \app\models\PurchaseBillItems $purchaseBillItems
 * @property \app\models\Tax $tax
 * @property string $aliasModel
 */
abstract class PurchaseBillItemsTax extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchase_bill_items_tax';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tax_id', 'rate', 'tax_amount'], 'required'],
            [['purchase_bill_items_id', 'tax_id'], 'integer'],
            [['rate', 'tax_amount'], 'number'],
            [['purchase_bill_items_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PurchaseBillItems::className(), 'targetAttribute' => ['purchase_bill_items_id' => 'id']],
            [['tax_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Tax::className(), 'targetAttribute' => ['tax_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'purchase_bill_items_id' => Yii::t('models', 'Purchase Bill Items'),
            'tax_id' => Yii::t('models', 'Tax'),
            'rate' => Yii::t('models', 'Rate'),
            'tax_amount' => Yii::t('models', 'Tax Amount'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchaseBillItems()
    {
        return $this->hasOne(\app\models\PurchaseBillItems::className(), ['id' => 'purchase_bill_items_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTax()
    {
        return $this->hasOne(\app\models\Tax::className(), ['id' => 'tax_id']);
    }




}
