<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "schedule_rate_master".
 *
 * @property integer $id
 * @property integer $srmid
 * @property integer $sno
 * @property string $type
 * @property string $item
 * @property string $hsn_no
 * @property integer $unit
 * @property integer $company_id
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Company $company
 * @property \app\models\Uom $unitName
 * @property string $aliasModel
 */
abstract class ScheduleRateMaster extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'schedule_rate_master';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'item', 'hsn_no', 'unit', 'company_id'], 'required'],
            [['unit', 'company_id','sno','srmid'], 'integer'],
            [['item'], 'string'],
            [['type'], 'string', 'max' => 255],
            [['hsn_no'], 'string', 'max' => 6],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['unit'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Uom::className(), 'targetAttribute' => ['unit' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'srmid' => 'Srmid',
            'sno' => 'S. No.',
            'type' => 'Type',
            'item' => 'Item',
            'hsn_no' => 'Hsn No',
            'unit' => 'Unit',
            'company_id' => 'Company',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnitName()
    {
        return $this->hasOne(\app\models\Uom::className(), ['id' => 'unit']);
    }




}
