<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "signature_master".
 *
 * @property integer $id
 * @property integer $company_id
 * @property integer $type_id
 * @property string $signature
 *
 * @property \app\models\Company $company
 * @property \app\models\SignatureType $type
 * @property string $aliasModel
 */
abstract class SignatureMaster extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'signature_master';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['company_id', 'type_id', 'signature'], 'required'],
            [['company_id', 'type_id'], 'integer'],
            [['signature'], 'string'],
            [['company_id', 'type_id'], 'unique', 'targetAttribute' => ['company_id', 'type_id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\SignatureType::className(), 'targetAttribute' => ['type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'company_id' => Yii::t('models', 'Company'),
            'type_id' => Yii::t('models', 'Type'),
            'signature' => Yii::t('models', 'Signature'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(\app\models\SignatureType::className(), ['id' => 'type_id']);
    }




}
