<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sites".
 *
 * @property integer $id
 * @property string $name
 * @property integer $state_id
 * @property integer $district_id
 * @property integer $company_id
 * @property integer $status
 *
 * @property \app\models\District $district
 * @property \app\models\State $state
 * @property \app\models\ContractCompany $company
 * @property string $aliasModel
 */
abstract class Sites extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sites';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'state_id', 'district_id'], 'required'],
            [['state_id', 'district_id','status'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['district_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\District::className(), 'targetAttribute' => ['district_id' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['state_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ContractCompany::className(), 'targetAttribute' => ['company_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'state_id' => Yii::t('models', 'State'),
            'district_id' => Yii::t('models', 'District'),
            'company_id' => Yii::t('models', 'Company'),
            'status' => Yii::t('models', 'Status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrict()
    {
        return $this->hasOne(\app\models\District::className(), ['id' => 'district_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'state_id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\ContractCompany::className(), ['id' => 'company_id']);
    }



}
