<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "state".
 *
 * @property integer $id
 * @property string $state
 * @property integer $state_tin
 * @property string $state_code
 * @property string $aliasModel
 */
abstract class State extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'state';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['state', 'state_tin', 'state_code'], 'required'],
            [['state_tin'], 'integer'],
            [['state'], 'string', 'max' => 100],
            [['state_code'], 'string', 'max' => 3]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'state' => Yii::t('models', 'State'),
            'state_tin' => Yii::t('models', 'State Tin'),
            'state_code' => Yii::t('models', 'State Code'),
        ];
    }




}
