<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "store_issue".
 *
 * @property integer $id
 * @property string $indent_no
 * @property string $date
 * @property integer $company_id
 * @property integer $state_id
 * @property integer $district_id
 * @property integer $site_id
 * @property integer $agreement_id
 * @property integer $billing_company_id
 * @property integer $status
 * @property string $session
 * @property string $comment
 * @property string $attachment_file
 * @property integer $form_head
 * @property string $form_account
 * @property integer $to_head
 * @property string $to_account
 * @property integer $worker_vendor
 * @property string $gate_pass_no
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\BillingCompany $billingCompany
 * @property \app\models\Company $company
 * @property \app\models\User $createdBy
 * @property \app\models\StoreIssueItems[] $storeIssueItems
 * @property \app\models\User $updatedBy
 * @property string $aliasModel
 */
abstract class StoreIssue extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'store_issue';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     * 
     */
    public function rules()
    {
        return [
            [['company_id', 'billing_company_id','state_id', 'district_id', 'site_id', 'agreement_id', 'session'], 'required'],
            [['company_id', 'billing_company_id','state_id', 'district_id', 'site_id', 'agreement_id', 'status','to_head','from_head','worker_vendor'], 'integer'],
            [['date','indent_no','comment','attachment_file','from_account','to_account','gate_pass_no'], 'safe'],
            [['session'], 'string', 'max' => 7],
            [['billing_company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BillingCompany::class, 'targetAttribute' => ['billing_company_id' => 'id']],
            [['agreement_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Agreement::class, 'targetAttribute' => ['agreement_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::class, 'targetAttribute' => ['company_id' => 'id']],
            [['district_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\District::class, 'targetAttribute' => ['district_id' => 'id']],
            [['site_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Sites::class, 'targetAttribute' => ['site_id' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::class, 'targetAttribute' => ['state_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::class, 'targetAttribute' => ['company_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::class, 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::class, 'targetAttribute' => ['updated_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'indent_no' => 'Indent No',
            'date' => 'Date',
            'company_id' => 'Company',
            'billing_company_id' => 'Billing Company',
            'state_id' => 'State',
            'district_id' => 'District',
            'site_id' => 'Site',
            'agreement_id' => 'Agreement',
            'session' => 'Session',
            'attachment_file'=>'Attachment File',
            'from_head'=>'Issue By',
            'from_account'=>'Issue By Account',
            'to_head'=>'Issue To',
            'to_account' => 'Issue To Account',
            'worker_vendor'=>'Worker Vendor',
            'gate_pass_no'=>'Gate Pass No',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillingCompany()
    {
        return $this->hasOne(\app\models\BillingCompany::class, ['id' => 'billing_company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::class, ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStoreIssueItems()
    {
        return $this->hasMany(\app\models\StoreIssueItems::class, ['store_issue_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'updated_by']);
    }

    public function getAgreement()
    {
        return $this->hasOne(\app\models\Agreement::class, ['id' => 'agreement_id']);
    }

    public function getDistrict()
    {
        return $this->hasOne(\app\models\District::class, ['id' => 'district_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSite()
    {
        return $this->hasOne(\app\models\Sites::class, ['id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\app\models\State::class, ['id' => 'state_id']);
    }




}
