<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "store_consumed_items".
 *
 * @property integer $id
 * @property integer $store_consumed_id
 * @property integer $store_products_id
 * @property integer $uom_id
 * @property integer $quantity
 * @property integer $status
 *
 * @property \app\models\StoreConsumed $storeConsumed
 * @property \app\models\StoreProducts $storeProducts
 * @property \app\models\Uom $uom
 * @property string $aliasModel
 */
abstract class StoreConsumedItems extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'store_consumed_items';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['store_products_id', 'uom_id', 'quantity'], 'required'],
            [['store_consumed_id', 'store_products_id', 'uom_id', 'quantity', 'status'], 'integer'],
            [['store_consumed_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StoreConsumed::class, 'targetAttribute' => ['store_consumed_id' => 'id']],
            [['store_products_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StoreProducts::class, 'targetAttribute' => ['store_products_id' => 'id']],
            [['uom_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Uom::class, 'targetAttribute' => ['uom_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'store_consumed_id' => 'Store Consumed',
            'store_products_id' => 'Store Products',
            'uom_id' => 'Uom',
            'quantity' => 'Quantity',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStoreConsumed()
    {
        return $this->hasOne(\app\models\StoreConsumed::class, ['id' => 'store_consumed_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStoreProducts()
    {
        return $this->hasOne(\app\models\StoreProducts::class, ['id' => 'store_products_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUom()
    {
        return $this->hasOne(\app\models\Uom::class, ['id' => 'uom_id']);
    }




}
