<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "store_issue_items".
 *
 * @property integer $id
 * @property integer $store_issue_id
 * @property integer $store_products_id
 * @property integer $gate_pass_no
 * @property integer $uom_id
 * @property integer $quantity
 * @property integer $status
 *
 * @property \app\models\StoreIssue $storeIssue
 * @property \app\models\StoreProducts $storeProducts
 * @property \app\models\Uom $uom
 * @property string $aliasModel
 */
abstract class StoreIssueItems extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'store_issue_items';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'store_products_id', 'uom_id', 'quantity'], 'required'],
            [['store_issue_id', 'store_products_id', 'gate_pass_no', 'uom_id', 'quantity', 'status'], 'integer'],
            [['store_issue_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StoreIssue::class, 'targetAttribute' => ['store_issue_id' => 'id']],
            [['store_products_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StoreProducts::class, 'targetAttribute' => ['store_products_id' => 'id']],
            [['uom_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Uom::class, 'targetAttribute' => ['uom_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'store_issue_id' => 'Store Issue',
            'store_products_id' => 'Store Products',
            'gate_pass_no' => 'Gate Pass No',
            'uom_id' => 'Uom',
            'quantity' => 'Quantity',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStoreIssue()
    {
        return $this->hasOne(\app\models\StoreIssue::class, ['id' => 'store_issue_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStoreProducts()
    {
        return $this->hasOne(\app\models\StoreProducts::class, ['id' => 'store_products_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUom()
    {
        return $this->hasOne(\app\models\Uom::class, ['id' => 'uom_id']);
    }

}
