<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "tax_ledger".
 *
 * @property integer $id
 * @property integer $page_id
 * @property integer $page
 * @property string $date
 * @property integer $tax_id
 * @property integer $tax_type
 * @property string $rate
 * @property string $amount
 * @property integer $inout
 * @property integer $status
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Company $company
 * @property \app\models\User $createdBy
 * @property \app\models\Tax $tax
 * @property \app\models\User $updatedBy
 * @property string $aliasModel
 */
abstract class TaxLedger extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tax_ledger';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['page_id', 'page', 'date', 'tax_id', 'tax_type', 'company_id', 'session'], 'required'],
            [['page_id', 'page', 'tax_id', 'tax_type', 'inout', 'status', 'company_id'], 'integer'],
            [['date'], 'safe'],
            [['rate', 'amount'], 'number'],
            [['session'], 'string', 'max' => 255],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['tax_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Tax::className(), 'targetAttribute' => ['tax_id' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['updated_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'page_id' => 'Page ID',
            'page' => 'Page',
            'date' => 'Date',
            'tax_id' => 'Tax ID',
            'tax_type' => 'Tax Type',
            'rate' => 'Rate',
            'amount' => 'Amount',
            'inout' => 'Inout',
            'status' => 'Status',
            'company_id' => 'Company ID',
            'session' => 'Session',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTax()
    {
        return $this->hasOne(\app\models\Tax::className(), ['id' => 'tax_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'updated_by']);
    }




}
