<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "vendor_bill_items".
 *
 * @property integer $id
 * @property integer $bill_id
 * @property integer $district_id
 * @property integer $site_id
 * @property string $particular
 * @property integer $work_type
 * @property integer $work_name
 * @property integer $uom_id
 * @property integer $hsn_no
 * @property string $quantity
 * @property string $rate
 * @property string $amount
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\VendorBill $bill
 * @property \app\models\Company $company
 * @property \app\models\District $district
 * @property \app\models\Sites $site
 * @property \app\models\WorkType $workType
 * @property \app\models\Work $workName
 * @property \app\models\Uom $uom
 * @property string $aliasModel
 */
abstract class VendorBillItems extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vendor_bill_items';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['bill_id', 'district_id', 'site_id', 'particular', 'quantity', 'rate', 'amount', 'company_id', 'session','uom_id'], 'required'],
            [['bill_id', 'district_id', 'site_id', 'work_type', 'work_name', 'company_id','hsn_no'], 'integer'],
            [['quantity', 'rate', 'amount'], 'number'],
            [['particular'], 'string', 'max' => 255],
            [['session'], 'string', 'max' => 7],
            [['bill_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\VendorBill::className(), 'targetAttribute' => ['bill_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['district_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\District::className(), 'targetAttribute' => ['district_id' => 'id']],
            [['site_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Sites::className(), 'targetAttribute' => ['site_id' => 'id']],
            [['work_type'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WorkType::className(), 'targetAttribute' => ['work_type' => 'id']],
            [['work_name'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Work::className(), 'targetAttribute' => ['work_name' => 'id']],
            [['uom_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Uom::className(), 'targetAttribute' => ['uom_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'bill_id' => Yii::t('models', 'Document No'),
            'district_id' => Yii::t('models', 'District'),
            'site_id' => Yii::t('models', 'Site'),
            'particular' => Yii::t('models', 'Particular'),
            'work_type' => Yii::t('models', 'Work Type'),
            'work_name' => Yii::t('models', 'Work Name'),
            'uom_id' => Yii::t('models', 'Unit'),
            'hsn_no' => Yii::t('models', 'Hsn No'),
            'quantity' => Yii::t('models', 'Quantity'),
            'rate' => Yii::t('models', 'Rate'),
            'amount' => Yii::t('models', 'Amount'),
            'company_id' => Yii::t('models', 'Company'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBill()
    {
        return $this->hasOne(\app\models\VendorBill::className(), ['id' => 'bill_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrict()
    {
        return $this->hasOne(\app\models\District::className(), ['id' => 'district_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSite()
    {
        return $this->hasOne(\app\models\Sites::className(), ['id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkType()
    {
        return $this->hasOne(\app\models\WorkType::className(), ['id' => 'work_type']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkName()
    {
        return $this->hasOne(\app\models\Work::className(), ['id' => 'work_name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUom()
    {
        return $this->hasOne(\app\models\Uom::className(), ['id' => 'uom_id']);
    }




}
