<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "vendor_bill_deduction".
 *
 * @property integer $id
 * @property integer $bill_id
 * @property integer $tax_id
 * @property string $rate
 * @property string $is_rate
 * @property string $amount
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\VendorBill $bill
 * @property \app\models\Company $company
 * @property \app\models\Tax $tax
 * @property string $aliasModel
 */
abstract class VendorBillDeduction extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vendor_bill_deduction';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            //[['bill_id', 'tax_id', 'rate', 'amount', 'company_id', 'session'], 'required'],
            [['bill_id', 'tax_id', 'company_id'], 'integer'],
            [['rate', 'amount','is_rate'], 'number'],
            [['session'], 'string', 'max' => 7],
            [['bill_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\VendorBill::className(), 'targetAttribute' => ['bill_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['tax_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Tax::className(), 'targetAttribute' => ['tax_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'bill_id' => Yii::t('models', 'Bill'),
            'tax_id' => Yii::t('models', 'Tax'),
            'rate' => Yii::t('models', 'Rate'),
            'is_rate' => Yii::t('models', 'Is Rate'),
            'amount' => Yii::t('models', 'Amount'),
            'company_id' => Yii::t('models', 'Company'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBill()
    {
        return $this->hasOne(\app\models\VendorBill::className(), ['id' => 'bill_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTax()
    {
        return $this->hasOne(\app\models\Tax::className(), ['id' => 'tax_id']);
    }




}
