<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "vendor_work_rate".
 *
 * @property integer $id
 * @property integer $vendor_id
 * @property integer $work_type
 * @property integer $work_name
 * @property string $rate
 * @property integer $company_id
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Company $company
 * @property \app\models\Vendor $vendor
 * @property \app\models\Work $workName
 * @property \app\models\WorkType $workType
 * @property string $aliasModel
 */
abstract class VendorWorkRate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vendor_work_rate';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['vendor_id', 'work_type', 'work_name', 'rate', 'company_id'], 'required'],
            [['vendor_id', 'work_type', 'work_name', 'company_id'], 'integer'],
            [['rate'], 'number'],
            [['vendor_id', 'work_type', 'work_name'], 'unique', 'targetAttribute' => ['vendor_id', 'work_type', 'work_name']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Vendor::className(), 'targetAttribute' => ['vendor_id' => 'id']],
            [['work_name'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Work::className(), 'targetAttribute' => ['work_name' => 'id']],
            [['work_type'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WorkType::className(), 'targetAttribute' => ['work_type' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'vendor_id' => 'Vendor',
            'work_type' => 'Work Type',
            'work_name' => 'Work Name',
            'rate' => 'Rate',
            'company_id' => 'Company',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Vendor::className(), ['id' => 'vendor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkName()
    {
        return $this->hasOne(\app\models\Work::className(), ['id' => 'work_name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkType()
    {
        return $this->hasOne(\app\models\WorkType::className(), ['id' => 'work_type']);
    }




}
