<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "vendor_bill".
 *
 * @property integer $id
 * @property integer $vendor_id
 * @property integer $bill_no
 * @property string $bill_date
 * @property string $invoice_no
 * @property string $invoice_date
 * @property string $base_amount
 * @property string $particular
 * @property integer $schedule
 * @property string $schedule_rate
 * @property string $schedule_amount
 * @property string $taxable_amount
 * @property string $tax_amount
 * @property string $payable_amount
 * @property string $deduction_amount
 * @property string $pay_amount
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Company $company
 * @property \app\models\Vendor $vendor
 * @property \app\models\VendorBillDeduction[] $vendorBillDeductions
 * @property \app\models\VendorBillItems[] $vendorBillItems
 * @property \app\models\VendorBillTax[] $vendorBillTaxes
 * @property string $aliasModel
 */
abstract class VendorBill extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vendor_bill';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['vendor_id', 'base_amount', 'taxable_amount', 'tax_amount', 'payable_amount', 'deduction_amount', 'pay_amount', 'company_id', 'session','bill_date'], 'required'],
            [['vendor_id', 'bill_no', 'schedule', 'company_id'], 'integer'],
            [['invoice_date','particular','invoice_no'], 'safe'],
            [['base_amount', 'schedule_rate', 'schedule_amount', 'taxable_amount', 'tax_amount', 'payable_amount', 'deduction_amount', 'pay_amount'], 'number'],
            [['session'], 'string', 'max' => 7],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Vendor::className(), 'targetAttribute' => ['vendor_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'vendor_id' => Yii::t('models', 'Vendor'),
            'bill_no' => Yii::t('models', 'Document No'),
            'bill_date' => Yii::t('models', 'Document Date'),
            'invoice_no' => Yii::t('models', 'Invoice No'),
            'invoice_date' => Yii::t('models', 'Invoice Date'),
            'base_amount' => Yii::t('models', 'Base Amount'),
            'particular' => Yii::t('models', 'Particular'),
            'schedule' => Yii::t('models', 'Schedule'),
            'schedule_rate' => Yii::t('models', 'Schedule Rate'),
            'schedule_amount' => Yii::t('models', 'Schedule Amount'),
            'taxable_amount' => Yii::t('models', 'Taxable Amount'),
            'tax_amount' => Yii::t('models', 'Tax Amount'),
            'payable_amount' => Yii::t('models', 'Payable Amount'),
            'deduction_amount' => Yii::t('models', 'Deduction Amount'),
            'pay_amount' => Yii::t('models', 'Pay Amount'),
            'company_id' => Yii::t('models', 'Company'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Vendor::className(), ['id' => 'vendor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendorBillDeductions()
    {
        return $this->hasMany(\app\models\VendorBillDeduction::className(), ['bill_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendorBillItems()
    {
        return $this->hasMany(\app\models\VendorBillItems::className(), ['bill_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendorBillTaxes()
    {
        return $this->hasMany(\app\models\VendorBillTax::className(), ['bill_id' => 'id']);
    }




}
