<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "worker_salary_allowance".
 *
 * @property integer $id
 * @property integer $worker_id
 * @property integer $salary_id
 * @property integer $allowance_id
 * @property string $actual_amount
 * @property string $per_day
 * @property string $amount
 *
 * @property \app\models\WorkerSalary $salary
 * @property \app\models\Worker $worker
 * @property \app\models\WorkerAllowance $allowance
 * @property string $aliasModel
 */
abstract class WorkerSalaryAllowance extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'worker_salary_allowance';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['worker_id', 'salary_id', 'allowance_id'], 'required'],
            [['worker_id', 'salary_id', 'allowance_id'], 'integer'],
            [['per_day', 'amount','actual_amount'], 'number'],
            [['salary_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WorkerSalary::className(), 'targetAttribute' => ['salary_id' => 'id']],
            [['worker_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Worker::className(), 'targetAttribute' => ['worker_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'worker_id' => Yii::t('models', 'Worker'),
            'salary_id' => Yii::t('models', 'Salary'),
            'allowance_id' => Yii::t('models', 'Allowance'),
            'actual_amount' => Yii::t('models', 'Actual Allowance'),
            'per_day' => Yii::t('models', 'Per Day'),
            'amount' => Yii::t('models', 'Amount'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSalary()
    {
        return $this->hasOne(\app\models\WorkerSalary::className(), ['id' => 'salary_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorker()
    {
        return $this->hasOne(\app\models\Worker::className(), ['id' => 'worker_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAllowance()
    {
        return $this->hasOne(\app\models\WorkerAllowance::className(), ['id' => 'allowance_id']);
    }




}
