<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "work".
 *
 * @property integer $id
 * @property string $name
 * @property integer $unit
 * @property integer $work_type
 *
 * @property \app\models\Uom $unitName
 * @property \app\models\WorkType $workType
 * @property string $aliasModel
 */
abstract class Work extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'work';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'unit', 'work_type'], 'required'],
            [['unit', 'work_type'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['unit'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Uom::className(), 'targetAttribute' => ['unit' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'unit' => Yii::t('models', 'Unit'),
            'work_type' => Yii::t('models', 'Work Type'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnitName()
    {
        return $this->hasOne(\app\models\Uom::className(), ['id' => 'unit']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkType()
    {
        return $this->hasOne(\app\models\WorkType::className(), ['id' => 'work_type']);
    }

}
