<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "worker_leave".
 *
 * @property integer $id
 * @property integer $worker_id
 * @property string $month
 * @property string $leave
 * @property string $comments
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Worker $worker
 * @property string $aliasModel
 */
abstract class WorkerLeave extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'worker_leave';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['worker_id', 'month'], 'required'],
            [['worker_id'], 'integer'],
            [['month'], 'safe'],
            [['leave', 'comments'], 'string'],
            [['worker_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Worker::className(), 'targetAttribute' => ['worker_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'worker_id' => Yii::t('models', 'Worker'),
            'month' => Yii::t('models', 'Month'),
            'leave' => Yii::t('models', 'Leave'),
            'comments' => Yii::t('models', 'Comments'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorker()
    {
        return $this->hasOne(\app\models\Worker::className(), ['id' => 'worker_id']);
    }




}
