<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "worker_salary_deduction".
 *
 * @property integer $id
 * @property integer $worker_id
 * @property integer $salary_id
 * @property integer $deduction_id
 * @property string $rate
 * @property string $per_day
 * @property string $amount
 *
 * @property \app\models\WorkerSalary $salary
 * @property \app\models\Worker $worker
 * @property \app\models\DeductionMaster $deduction
 * @property string $aliasModel
 */
abstract class WorkerSalaryDeduction extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'worker_salary_deduction';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['worker_id', 'salary_id', 'deduction_id'], 'required'],
            [['worker_id', 'salary_id', 'deduction_id'], 'integer'],
            [['rate', 'per_day', 'amount'], 'number'],
            [['salary_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WorkerSalary::className(), 'targetAttribute' => ['salary_id' => 'id']],
            [['worker_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Worker::className(), 'targetAttribute' => ['worker_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'worker_id' => Yii::t('models', 'Worker ID'),
            'salary_id' => Yii::t('models', 'Salary ID'),
            'deduction_id' => Yii::t('models', 'Deduction ID'),
            'rate' => Yii::t('models', 'Rate'),
            'per_day' => Yii::t('models', 'Per Day'),
            'amount' => Yii::t('models', 'Amount'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSalary()
    {
        return $this->hasOne(\app\models\WorkerSalary::className(), ['id' => 'salary_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorker()
    {
        return $this->hasOne(\app\models\Worker::className(), ['id' => 'worker_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getdeduction()
    {
        return $this->hasOne(\app\models\DeductionMaster::className(), ['id' => 'deduction_id']);
    }





}
