<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "worker_vendor".
 *
 * @property integer $id
 * @property string $name
 * @property integer $code
 * @property string $father_name
 * @property string $mobile
 * @property string $pancard_no
 * @property string $aadhar_no
 * @property string $address
 * @property integer $state_id
 * @property integer $district_id
 * @property string $pincode
 * @property integer $commission_type
 * @property string $commission
 * @property string $last_balance
 * @property integer $inout_type
 * @property string $joining_date
 * @property integer $status
 * @property integer $company_id
 * @property string $session
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Company $company
 * @property \app\models\District $district
 * @property \app\models\State $state
 * @property \app\models\Account $account
 * @property \app\models\Document $document
 * @property string $aliasModel
 */
abstract class WorkerVendor extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'worker_vendor';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name','father_name', 'address', 'state_id', 'district_id', 'pincode', 'commission_type', 'commission', 'inout_type', 'joining_date', 'company_id', 'session','status'], 'required'],
            [['code','state_id', 'district_id', 'commission_type', 'inout_type', 'status', 'company_id'], 'integer'],
            [['commission', 'last_balance'], 'number'],
            [['joining_date'], 'safe'],
            [['name', 'father_name', 'address'], 'string', 'max' => 255],
            [['mobile'], 'string', 'max' => 10],
            [['pancard_no'], 'string', 'max' => 15],
            [['aadhar_no'], 'string', 'max' => 12],
            [['pincode'], 'string', 'max' => 6],
            [['session'], 'string', 'max' => 7],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['district_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\District::className(), 'targetAttribute' => ['district_id' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\State::className(), 'targetAttribute' => ['state_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'code' => Yii::t('models', 'Code'),
            'father_name' => Yii::t('models', 'Father Name'),
            'mobile' => Yii::t('models', 'Mobile'),
            'pancard_no' => Yii::t('models', 'Pancard No'),
            'aadhar_no' => Yii::t('models', 'Aadhar No'),
            'address' => Yii::t('models', 'Address'),
            'state_id' => Yii::t('models', 'State'),
            'district_id' => Yii::t('models', 'District'),
            'pincode' => Yii::t('models', 'Pincode'),
            'commission_type' => Yii::t('models', 'Commission Type'),
            'commission' => Yii::t('models', 'Commission'),
            'last_balance' => Yii::t('models', 'Last Balance'),
            'inout_type' => Yii::t('models', 'Inout Type'),
            'joining_date' => Yii::t('models', 'Joining Date'),
            'status' => Yii::t('models', 'Status'),
            'company_id' => Yii::t('models', 'Company'),
            'session' => Yii::t('models', 'Session'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrict()
    {
        return $this->hasOne(\app\models\District::className(), ['id' => 'district_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\app\models\State::className(), ['id' => 'state_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocument()
    {
        return $this->hasMany(\app\models\Document::className(), ['worker_vendor_id' => 'id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccount()
    {
        return $this->hasMany(\app\models\Account::className(), ['worker_vendor_id' => 'id']);
    }

}
