<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "worker_allowance".
 *
 * @property integer $id
 * @property integer $worker_id
 * @property integer $allowance_id
 * @property string $value
 *
 * @property \app\models\AllowanceMaster $allowance
 * @property \app\models\Worker $worker
 * @property string $aliasModel
 */
abstract class WorkerAllowance extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'worker_allowance';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['worker_id', 'allowance_id'], 'required'],
            [['worker_id', 'allowance_id'], 'integer'],
            [['value'], 'number'],
            [['allowance_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\AllowanceMaster::className(), 'targetAttribute' => ['allowance_id' => 'id']],
            [['worker_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Worker::className(), 'targetAttribute' => ['worker_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'worker_id' => Yii::t('models', 'Worker ID'),
            'allowance_id' => Yii::t('models', 'Allowance ID'),
            'value' => Yii::t('models', 'Value'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAllowance()
    {
        return $this->hasOne(\app\models\AllowanceMaster::className(), ['id' => 'allowance_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorker()
    {
        return $this->hasOne(\app\models\Worker::className(), ['id' => 'worker_id']);
    }




}
